entero n1, n2, n3
cadena [20]correo
cadena [20]clave
inicio
	n1<-3
	mientras (n1>0) haga
		escriba "tienes:", n1, "intentos"
		escriba "ingrese su usuario"
		llamar nueva_linea
		lea correo
		escriba "ingrese su clave"
		llamar nueva_linea
		lea clave
		llamar nueva_linea
		si   (correo="lucas@melon") y (clave="113") haga
		escriba "bienvenido"
		n1<-0
		sino
		escriba "datos incorrectos"
		
		
	
fin si
	n1<-n1-1
fin mientras
fin
	